apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: <client-id>   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: <key-vault-name>        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret
          objectVersion: ""
    tenantId: <tenant-id>                 # The tenant ID of the key vault

  # Kubernetes Secret も作成する場合 (Optional)
  # secretObjects:
  #   - data:
  #       - objectName: ExampleSecret
  #         key: example-secret             # Secret の data のキー名（例: base64 で入る）
  #     secretName: my-secret-from-kv       # 作成される Secret の名前
  #     type: Opaque
